/* linemarks.c generated by valac 0.44.5, the Vala compiler
 * generated from linemarks.vala, do not modify */

#include <glib-object.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <glib.h>
#include <gobject/gvaluecollector.h>
#include <gtk/gtk.h>
#include <string.h>
#include <gtksourceview/gtksourceview.h>
#include <pango/pango.h>
#include <gdk/gdk.h>
#include <cairo.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>

#define TYPE_PIXBUF_WITH_CACHE (pixbuf_with_cache_get_type ())
#define PIXBUF_WITH_CACHE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PIXBUF_WITH_CACHE, PixbufWithCache))
#define PIXBUF_WITH_CACHE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PIXBUF_WITH_CACHE, PixbufWithCacheClass))
#define IS_PIXBUF_WITH_CACHE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PIXBUF_WITH_CACHE))
#define IS_PIXBUF_WITH_CACHE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PIXBUF_WITH_CACHE))
#define PIXBUF_WITH_CACHE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PIXBUF_WITH_CACHE, PixbufWithCacheClass))

typedef struct _PixbufWithCache PixbufWithCache;
typedef struct _PixbufWithCacheClass PixbufWithCacheClass;
typedef struct _PixbufWithCachePrivate PixbufWithCachePrivate;
#define _pixbuf_with_cache_unref0(var) ((var == NULL) ? NULL : (var = (pixbuf_with_cache_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _ParamSpecPixbufWithCache ParamSpecPixbufWithCache;

#define TYPE_LINE_MARK (line_mark_get_type ())
#define LINE_MARK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_LINE_MARK, LineMark))
#define LINE_MARK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_LINE_MARK, LineMarkClass))
#define IS_LINE_MARK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_LINE_MARK))
#define IS_LINE_MARK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_LINE_MARK))
#define LINE_MARK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_LINE_MARK, LineMarkClass))

typedef struct _LineMark LineMark;
typedef struct _LineMarkClass LineMarkClass;
typedef struct _LineMarkPrivate LineMarkPrivate;
typedef struct _ParamSpecLineMark ParamSpecLineMark;

#define TYPE_LINE_MARKS_TABLE (line_marks_table_get_type ())
#define LINE_MARKS_TABLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_LINE_MARKS_TABLE, LineMarksTable))
#define LINE_MARKS_TABLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_LINE_MARKS_TABLE, LineMarksTableClass))
#define IS_LINE_MARKS_TABLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_LINE_MARKS_TABLE))
#define IS_LINE_MARKS_TABLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_LINE_MARKS_TABLE))
#define LINE_MARKS_TABLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_LINE_MARKS_TABLE, LineMarksTableClass))

typedef struct _LineMarksTable LineMarksTable;
typedef struct _LineMarksTableClass LineMarksTableClass;
typedef struct _LineMarksTablePrivate LineMarksTablePrivate;
enum  {
	LINE_MARKS_TABLE_0_PROPERTY,
	LINE_MARKS_TABLE_NUM_PROPERTIES
};
static GParamSpec* line_marks_table_properties[LINE_MARKS_TABLE_NUM_PROPERTIES];
#define _line_mark_unref0(var) ((var == NULL) ? NULL : (var = (line_mark_unref (var), NULL)))

#define TYPE_LINE_MARKS_RENDERER (line_marks_renderer_get_type ())
#define LINE_MARKS_RENDERER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_LINE_MARKS_RENDERER, LineMarksRenderer))
#define LINE_MARKS_RENDERER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_LINE_MARKS_RENDERER, LineMarksRendererClass))
#define IS_LINE_MARKS_RENDERER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_LINE_MARKS_RENDERER))
#define IS_LINE_MARKS_RENDERER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_LINE_MARKS_RENDERER))
#define LINE_MARKS_RENDERER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_LINE_MARKS_RENDERER, LineMarksRendererClass))

typedef struct _LineMarksRenderer LineMarksRenderer;
typedef struct _LineMarksRendererClass LineMarksRendererClass;
typedef struct _LineMarksRendererPrivate LineMarksRendererPrivate;
enum  {
	LINE_MARKS_RENDERER_0_PROPERTY,
	LINE_MARKS_RENDERER_NUM_PROPERTIES
};
static GParamSpec* line_marks_renderer_properties[LINE_MARKS_RENDERER_NUM_PROPERTIES];
#define _cairo_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_destroy (var), NULL)))

#define TYPE_SOURCE_GUTTER_TEXT_COLUMN (source_gutter_text_column_get_type ())
#define SOURCE_GUTTER_TEXT_COLUMN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SOURCE_GUTTER_TEXT_COLUMN, SourceGutterTextColumn))
#define SOURCE_GUTTER_TEXT_COLUMN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SOURCE_GUTTER_TEXT_COLUMN, SourceGutterTextColumnClass))
#define IS_SOURCE_GUTTER_TEXT_COLUMN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SOURCE_GUTTER_TEXT_COLUMN))
#define IS_SOURCE_GUTTER_TEXT_COLUMN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SOURCE_GUTTER_TEXT_COLUMN))
#define SOURCE_GUTTER_TEXT_COLUMN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SOURCE_GUTTER_TEXT_COLUMN, SourceGutterTextColumnClass))

typedef struct _SourceGutterTextColumn SourceGutterTextColumn;
typedef struct _SourceGutterTextColumnClass SourceGutterTextColumnClass;
typedef struct _SourceGutterTextColumnPrivate SourceGutterTextColumnPrivate;
enum  {
	SOURCE_GUTTER_TEXT_COLUMN_0_PROPERTY,
	SOURCE_GUTTER_TEXT_COLUMN_NUM_PROPERTIES
};
static GParamSpec* source_gutter_text_column_properties[SOURCE_GUTTER_TEXT_COLUMN_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))

struct _PixbufWithCache {
	GTypeInstance parent_instance;
	volatile int ref_count;
	PixbufWithCachePrivate * priv;
	PixbufWithCache* next;
	GdkPixbuf* original;
	gint scaledSize;
	GdkPixbuf* scaled;
};

struct _PixbufWithCacheClass {
	GTypeClass parent_class;
	void (*finalize) (PixbufWithCache *self);
};

struct _ParamSpecPixbufWithCache {
	GParamSpec parent_instance;
};

struct _LineMark {
	GTypeInstance parent_instance;
	volatile int ref_count;
	LineMarkPrivate * priv;
	GtkTextMark* textMark;
	PixbufWithCache* pixbuf;
	gint line;
	gint column;
};

struct _LineMarkClass {
	GTypeClass parent_class;
	void (*finalize) (LineMark *self);
};

struct _ParamSpecLineMark {
	GParamSpec parent_instance;
};

struct _LineMarksTable {
	GObject parent_instance;
	LineMarksTablePrivate * priv;
	LineMark** lineMarks;
	gint lineMarks_length1;
	gint _lineMarks_size_;
	gint lineHeight;
	gint rendererWidth;
	GtkTextBuffer* lastBuffer;
	gint lastLineNumber;
	gint nextIndex;
	gint lineNumber;
};

struct _LineMarksTableClass {
	GObjectClass parent_class;
};

struct _LineMarksTablePrivate {
	PixbufWithCache* pixbufCache;
	gboolean sorted;
};

struct _LineMarksRenderer {
	GtkCellRenderer parent_instance;
	LineMarksRendererPrivate * priv;
};

struct _LineMarksRendererClass {
	GtkCellRendererClass parent_class;
};

struct _LineMarksRendererPrivate {
	LineMarksTable* table;
	GtkSourceGutter* gutter;
};

struct _SourceGutterTextColumn {
	GObject parent_instance;
	SourceGutterTextColumnPrivate * priv;
};

struct _SourceGutterTextColumnClass {
	GObjectClass parent_class;
};

struct _SourceGutterTextColumnPrivate {
	gchar* sizeText;
	gchar** lines;
	gint lines_length1;
	gint _lines_size_;
	GtkCellRendererText* renderer;
	GtkSourceGutter** gutters;
	gint gutters_length1;
	gint _gutters_size_;
};

static gpointer pixbuf_with_cache_parent_class = NULL;
static gpointer line_mark_parent_class = NULL;
static gint LineMarksTable_private_offset;
static gpointer line_marks_table_parent_class = NULL;
static gint LineMarksRenderer_private_offset;
static gpointer line_marks_renderer_parent_class = NULL;
static gint SourceGutterTextColumn_private_offset;
static gpointer source_gutter_text_column_parent_class = NULL;

gpointer pixbuf_with_cache_ref (gpointer instance);
void pixbuf_with_cache_unref (gpointer instance);
GParamSpec* param_spec_pixbuf_with_cache (const gchar* name,
                                          const gchar* nick,
                                          const gchar* blurb,
                                          GType object_type,
                                          GParamFlags flags);
void value_set_pixbuf_with_cache (GValue* value,
                                  gpointer v_object);
void value_take_pixbuf_with_cache (GValue* value,
                                   gpointer v_object);
gpointer value_get_pixbuf_with_cache (const GValue* value);
GType pixbuf_with_cache_get_type (void) G_GNUC_CONST;
PixbufWithCache* pixbuf_with_cache_new (PixbufWithCache* next,
                                        GdkPixbuf* original);
PixbufWithCache* pixbuf_with_cache_construct (GType object_type,
                                              PixbufWithCache* next,
                                              GdkPixbuf* original);
GdkPixbuf* pixbuf_with_cache_get_at_size (PixbufWithCache* self,
                                          gint size);
static void pixbuf_with_cache_finalize (PixbufWithCache * obj);
gpointer line_mark_ref (gpointer instance);
void line_mark_unref (gpointer instance);
GParamSpec* param_spec_line_mark (const gchar* name,
                                  const gchar* nick,
                                  const gchar* blurb,
                                  GType object_type,
                                  GParamFlags flags);
void value_set_line_mark (GValue* value,
                          gpointer v_object);
void value_take_line_mark (GValue* value,
                           gpointer v_object);
gpointer value_get_line_mark (const GValue* value);
GType line_mark_get_type (void) G_GNUC_CONST;
LineMark* line_mark_new (GtkTextMark* textMark,
                         PixbufWithCache* pixbuf);
LineMark* line_mark_construct (GType object_type,
                               GtkTextMark* textMark,
                               PixbufWithCache* pixbuf);
void line_mark_update_line_column_cache (LineMark* self);
static void line_mark_finalize (LineMark * obj);
GType line_marks_table_get_type (void) G_GNUC_CONST;
static PixbufWithCache* line_marks_table_get_pixbuf_with_cache (LineMarksTable* self,
                                                         GdkPixbuf* pixbuf);
void line_marks_table_clear (LineMarksTable* self);
static void line_marks_table_update_line_marks_line_column_cache (LineMarksTable* self);
static gint line_marks_table_compare_line_marks (LineMark** m1,
                                          LineMark** m2);
static void line_marks_table_sort_line_marks (LineMarksTable* self);
static gint _line_marks_table_compare_line_marks_gcompare_data_func (gconstpointer a,
                                                              gconstpointer b,
                                                              gpointer self);
void line_marks_table_add_line_mark (LineMarksTable* self,
                                     GtkTextMark* textMark,
                                     GdkPixbuf* pixbuf);
static void _vala_array_add1 (LineMark** * array,
                       int* length,
                       int* size,
                       LineMark* value);
void line_marks_table_add_line_mark_at_line_offset (LineMarksTable* self,
                                                    GtkTextBuffer* buffer,
                                                    gint line,
                                                    gint offset,
                                                    GdkPixbuf* pixbuf);
static gint line_marks_table_measure_line_height (LineMarksTable* self,
                                           GtkSourceView* view);
static gint line_marks_table_get_max_nb_marks_on_line (LineMarksTable* self,
                                                GtkTextBuffer* buffer);
static void line_marks_table_size_func (LineMarksTable* self,
                                 GtkSourceGutter* gutter,
                                 GtkCellRenderer* renderer);
static void line_marks_table_data_func (LineMarksTable* self,
                                 GtkSourceGutter* gutter,
                                 GtkCellRenderer* renderer,
                                 gint lineNumber,
                                 gboolean currentLine);
void line_marks_table_show_in_source_view (LineMarksTable* self,
                                           GtkSourceView* sourceView);
GType line_marks_renderer_get_type (void) G_GNUC_CONST;
LineMarksRenderer* line_marks_renderer_new (LineMarksTable* table,
                                            GtkSourceGutter* gutter);
LineMarksRenderer* line_marks_renderer_construct (GType object_type,
                                                  LineMarksTable* table,
                                                  GtkSourceGutter* gutter);
static void _line_marks_table_size_func_gtk_source_gutter_size_func (GtkSourceGutter* gutter,
                                                              GtkCellRenderer* cell,
                                                              gpointer self);
static void _line_marks_table_data_func_gtk_source_gutter_data_func (GtkSourceGutter* gutter,
                                                              GtkCellRenderer* cell,
                                                              gint line_number,
                                                              gboolean current_line,
                                                              gpointer self);
LineMarksTable* line_marks_table_new (void);
LineMarksTable* line_marks_table_construct (GType object_type);
static void line_marks_table_finalize (GObject * obj);
static void line_marks_renderer_real_get_size (GtkCellRenderer* base,
                                        GtkWidget* widget,
                                        GdkRectangle* cell_area,
                                        gint* x_offset,
                                        gint* y_offset,
                                        gint* width,
                                        gint* height);
static void line_marks_renderer_real_render (GtkCellRenderer* base,
                                      GdkWindow* window,
                                      GtkWidget* widget,
                                      GdkRectangle* background_area,
                                      GdkRectangle* cell_area,
                                      GdkRectangle* expose_area,
                                      GtkCellRendererState flags);
static void line_marks_renderer_finalize (GObject * obj);
GType source_gutter_text_column_get_type (void) G_GNUC_CONST;
SourceGutterTextColumn* source_gutter_text_column_new (const gchar* sizeText,
                                                       gfloat xalign);
SourceGutterTextColumn* source_gutter_text_column_construct (GType object_type,
                                                             const gchar* sizeText,
                                                             gfloat xalign);
void source_gutter_text_column_clear (SourceGutterTextColumn* self);
void source_gutter_text_column_add_line (SourceGutterTextColumn* self,
                                         const gchar* line);
static void _vala_array_add2 (gchar** * array,
                       int* length,
                       int* size,
                       gchar* value);
static void source_gutter_text_column_size_func (SourceGutterTextColumn* self,
                                          GtkSourceGutter* gutter,
                                          GtkCellRenderer* renderer_);
static void source_gutter_text_column_data_func (SourceGutterTextColumn* self,
                                          GtkSourceGutter* gutter,
                                          GtkCellRenderer* renderer_,
                                          gint lineNumber,
                                          gboolean currentLine);
void source_gutter_text_column_show_in_source_view (SourceGutterTextColumn* self,
                                                    GtkSourceView* sourceView);
static void _vala_array_add3 (GtkSourceGutter** * array,
                       int* length,
                       int* size,
                       GtkSourceGutter* value);
static void _source_gutter_text_column_size_func_gtk_source_gutter_size_func (GtkSourceGutter* gutter,
                                                                       GtkCellRenderer* cell,
                                                                       gpointer self);
static void _source_gutter_text_column_data_func_gtk_source_gutter_data_func (GtkSourceGutter* gutter,
                                                                       GtkCellRenderer* cell,
                                                                       gint line_number,
                                                                       gboolean current_line,
                                                                       gpointer self);
static void source_gutter_text_column_finalize (GObject * obj);
static void _vala_array_destroy (gpointer array,
                          gint array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gint array_length,
                       GDestroyNotify destroy_func);

static gpointer
_pixbuf_with_cache_ref0 (gpointer self)
{
	return self ? pixbuf_with_cache_ref (self) : NULL;
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

PixbufWithCache*
pixbuf_with_cache_construct (GType object_type,
                             PixbufWithCache* next,
                             GdkPixbuf* original)
{
	PixbufWithCache* self = NULL;
	PixbufWithCache* _tmp0_;
	GdkPixbuf* _tmp1_;
	g_return_val_if_fail (original != NULL, NULL);
	self = (PixbufWithCache*) g_type_create_instance (object_type);
	_tmp0_ = _pixbuf_with_cache_ref0 (next);
	_pixbuf_with_cache_unref0 (self->next);
	self->next = _tmp0_;
	_tmp1_ = _g_object_ref0 (original);
	_g_object_unref0 (self->original);
	self->original = _tmp1_;
	self->scaledSize = -1;
	_g_object_unref0 (self->scaled);
	self->scaled = NULL;
	return self;
}

PixbufWithCache*
pixbuf_with_cache_new (PixbufWithCache* next,
                       GdkPixbuf* original)
{
	return pixbuf_with_cache_construct (TYPE_PIXBUF_WITH_CACHE, next, original);
}

GdkPixbuf*
pixbuf_with_cache_get_at_size (PixbufWithCache* self,
                               gint size)
{
	GdkPixbuf* result = NULL;
	GdkPixbuf* _tmp2_;
	GdkPixbuf* _tmp3_;
	g_return_val_if_fail (self != NULL, NULL);
	if (self->scaledSize != size) {
		GdkPixbuf* _tmp0_;
		GdkPixbuf* _tmp1_;
		_tmp0_ = self->original;
		_tmp1_ = gdk_pixbuf_scale_simple (_tmp0_, size, size, GDK_INTERP_BILINEAR);
		_g_object_unref0 (self->scaled);
		self->scaled = _tmp1_;
		self->scaledSize = size;
	}
	_tmp2_ = self->scaled;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	result = _tmp3_;
	return result;
}

static void
value_pixbuf_with_cache_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
value_pixbuf_with_cache_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		pixbuf_with_cache_unref (value->data[0].v_pointer);
	}
}

static void
value_pixbuf_with_cache_copy_value (const GValue* src_value,
                                    GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = pixbuf_with_cache_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
value_pixbuf_with_cache_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
value_pixbuf_with_cache_collect_value (GValue* value,
                                       guint n_collect_values,
                                       GTypeCValue* collect_values,
                                       guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		PixbufWithCache * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = pixbuf_with_cache_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
value_pixbuf_with_cache_lcopy_value (const GValue* value,
                                     guint n_collect_values,
                                     GTypeCValue* collect_values,
                                     guint collect_flags)
{
	PixbufWithCache ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = pixbuf_with_cache_ref (value->data[0].v_pointer);
	}
	return NULL;
}

GParamSpec*
param_spec_pixbuf_with_cache (const gchar* name,
                              const gchar* nick,
                              const gchar* blurb,
                              GType object_type,
                              GParamFlags flags)
{
	ParamSpecPixbufWithCache* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_PIXBUF_WITH_CACHE), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

gpointer
value_get_pixbuf_with_cache (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_PIXBUF_WITH_CACHE), NULL);
	return value->data[0].v_pointer;
}

void
value_set_pixbuf_with_cache (GValue* value,
                             gpointer v_object)
{
	PixbufWithCache * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_PIXBUF_WITH_CACHE));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_PIXBUF_WITH_CACHE));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		pixbuf_with_cache_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		pixbuf_with_cache_unref (old);
	}
}

void
value_take_pixbuf_with_cache (GValue* value,
                              gpointer v_object)
{
	PixbufWithCache * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_PIXBUF_WITH_CACHE));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_PIXBUF_WITH_CACHE));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		pixbuf_with_cache_unref (old);
	}
}

static void
pixbuf_with_cache_class_init (PixbufWithCacheClass * klass,
                              gpointer klass_data)
{
	pixbuf_with_cache_parent_class = g_type_class_peek_parent (klass);
	((PixbufWithCacheClass *) klass)->finalize = pixbuf_with_cache_finalize;
}

static void
pixbuf_with_cache_instance_init (PixbufWithCache * self,
                                 gpointer klass)
{
	self->ref_count = 1;
}

static void
pixbuf_with_cache_finalize (PixbufWithCache * obj)
{
	PixbufWithCache * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_PIXBUF_WITH_CACHE, PixbufWithCache);
	g_signal_handlers_destroy (self);
	_pixbuf_with_cache_unref0 (self->next);
	_g_object_unref0 (self->original);
	_g_object_unref0 (self->scaled);
}

GType
pixbuf_with_cache_get_type (void)
{
	static volatile gsize pixbuf_with_cache_type_id__volatile = 0;
	if (g_once_init_enter (&pixbuf_with_cache_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_pixbuf_with_cache_init, value_pixbuf_with_cache_free_value, value_pixbuf_with_cache_copy_value, value_pixbuf_with_cache_peek_pointer, "p", value_pixbuf_with_cache_collect_value, "p", value_pixbuf_with_cache_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (PixbufWithCacheClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) pixbuf_with_cache_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PixbufWithCache), 0, (GInstanceInitFunc) pixbuf_with_cache_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType pixbuf_with_cache_type_id;
		pixbuf_with_cache_type_id = g_type_register_fundamental (g_type_fundamental_next (), "PixbufWithCache", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&pixbuf_with_cache_type_id__volatile, pixbuf_with_cache_type_id);
	}
	return pixbuf_with_cache_type_id__volatile;
}

gpointer
pixbuf_with_cache_ref (gpointer instance)
{
	PixbufWithCache * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

void
pixbuf_with_cache_unref (gpointer instance)
{
	PixbufWithCache * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		PIXBUF_WITH_CACHE_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

LineMark*
line_mark_construct (GType object_type,
                     GtkTextMark* textMark,
                     PixbufWithCache* pixbuf)
{
	LineMark* self = NULL;
	GtkTextMark* _tmp0_;
	PixbufWithCache* _tmp1_;
	g_return_val_if_fail (textMark != NULL, NULL);
	g_return_val_if_fail (pixbuf != NULL, NULL);
	self = (LineMark*) g_type_create_instance (object_type);
	_tmp0_ = _g_object_ref0 (textMark);
	_g_object_unref0 (self->textMark);
	self->textMark = _tmp0_;
	_tmp1_ = _pixbuf_with_cache_ref0 (pixbuf);
	_pixbuf_with_cache_unref0 (self->pixbuf);
	self->pixbuf = _tmp1_;
	return self;
}

LineMark*
line_mark_new (GtkTextMark* textMark,
               PixbufWithCache* pixbuf)
{
	return line_mark_construct (TYPE_LINE_MARK, textMark, pixbuf);
}

void
line_mark_update_line_column_cache (LineMark* self)
{
	GtkTextIter iter = {0};
	GtkTextMark* _tmp0_;
	GtkTextBuffer* _tmp1_;
	GtkTextMark* _tmp2_;
	GtkTextIter _tmp3_ = {0};
	g_return_if_fail (self != NULL);
	_tmp0_ = self->textMark;
	_tmp1_ = gtk_text_mark_get_buffer (_tmp0_);
	_tmp2_ = self->textMark;
	gtk_text_buffer_get_iter_at_mark (_tmp1_, &_tmp3_, _tmp2_);
	iter = _tmp3_;
	self->line = gtk_text_iter_get_line (&iter);
	self->column = gtk_text_iter_get_line_offset (&iter);
}

static void
value_line_mark_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
value_line_mark_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		line_mark_unref (value->data[0].v_pointer);
	}
}

static void
value_line_mark_copy_value (const GValue* src_value,
                            GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = line_mark_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
value_line_mark_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
value_line_mark_collect_value (GValue* value,
                               guint n_collect_values,
                               GTypeCValue* collect_values,
                               guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		LineMark * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = line_mark_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
value_line_mark_lcopy_value (const GValue* value,
                             guint n_collect_values,
                             GTypeCValue* collect_values,
                             guint collect_flags)
{
	LineMark ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = line_mark_ref (value->data[0].v_pointer);
	}
	return NULL;
}

GParamSpec*
param_spec_line_mark (const gchar* name,
                      const gchar* nick,
                      const gchar* blurb,
                      GType object_type,
                      GParamFlags flags)
{
	ParamSpecLineMark* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_LINE_MARK), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

gpointer
value_get_line_mark (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_LINE_MARK), NULL);
	return value->data[0].v_pointer;
}

void
value_set_line_mark (GValue* value,
                     gpointer v_object)
{
	LineMark * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_LINE_MARK));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_LINE_MARK));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		line_mark_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		line_mark_unref (old);
	}
}

void
value_take_line_mark (GValue* value,
                      gpointer v_object)
{
	LineMark * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_LINE_MARK));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_LINE_MARK));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		line_mark_unref (old);
	}
}

static void
line_mark_class_init (LineMarkClass * klass,
                      gpointer klass_data)
{
	line_mark_parent_class = g_type_class_peek_parent (klass);
	((LineMarkClass *) klass)->finalize = line_mark_finalize;
}

static void
line_mark_instance_init (LineMark * self,
                         gpointer klass)
{
	self->ref_count = 1;
}

static void
line_mark_finalize (LineMark * obj)
{
	LineMark * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_LINE_MARK, LineMark);
	g_signal_handlers_destroy (self);
	_g_object_unref0 (self->textMark);
	_pixbuf_with_cache_unref0 (self->pixbuf);
}

GType
line_mark_get_type (void)
{
	static volatile gsize line_mark_type_id__volatile = 0;
	if (g_once_init_enter (&line_mark_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_line_mark_init, value_line_mark_free_value, value_line_mark_copy_value, value_line_mark_peek_pointer, "p", value_line_mark_collect_value, "p", value_line_mark_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (LineMarkClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) line_mark_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LineMark), 0, (GInstanceInitFunc) line_mark_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType line_mark_type_id;
		line_mark_type_id = g_type_register_fundamental (g_type_fundamental_next (), "LineMark", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&line_mark_type_id__volatile, line_mark_type_id);
	}
	return line_mark_type_id__volatile;
}

gpointer
line_mark_ref (gpointer instance)
{
	LineMark * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

void
line_mark_unref (gpointer instance)
{
	LineMark * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		LINE_MARK_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

static inline gpointer
line_marks_table_get_instance_private (LineMarksTable* self)
{
	return G_STRUCT_MEMBER_P (self, LineMarksTable_private_offset);
}

static PixbufWithCache*
line_marks_table_get_pixbuf_with_cache (LineMarksTable* self,
                                        GdkPixbuf* pixbuf)
{
	PixbufWithCache* result = NULL;
	PixbufWithCache* cache = NULL;
	PixbufWithCache* _tmp0_;
	PixbufWithCache* _tmp1_;
	PixbufWithCache* _tmp9_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (pixbuf != NULL, NULL);
	_tmp0_ = self->priv->pixbufCache;
	_tmp1_ = _pixbuf_with_cache_ref0 (_tmp0_);
	cache = _tmp1_;
	while (TRUE) {
		gboolean _tmp2_ = FALSE;
		PixbufWithCache* _tmp3_;
		PixbufWithCache* _tmp6_;
		PixbufWithCache* _tmp7_;
		PixbufWithCache* _tmp8_;
		_tmp3_ = cache;
		if (_tmp3_ != NULL) {
			PixbufWithCache* _tmp4_;
			GdkPixbuf* _tmp5_;
			_tmp4_ = cache;
			_tmp5_ = _tmp4_->original;
			_tmp2_ = _tmp5_ != pixbuf;
		} else {
			_tmp2_ = FALSE;
		}
		if (!_tmp2_) {
			break;
		}
		_tmp6_ = cache;
		_tmp7_ = _tmp6_->next;
		_tmp8_ = _pixbuf_with_cache_ref0 (_tmp7_);
		_pixbuf_with_cache_unref0 (cache);
		cache = _tmp8_;
	}
	_tmp9_ = cache;
	if (_tmp9_ == NULL) {
		PixbufWithCache* _tmp10_;
		PixbufWithCache* _tmp11_;
		PixbufWithCache* _tmp12_;
		PixbufWithCache* _tmp13_;
		_tmp10_ = self->priv->pixbufCache;
		_tmp11_ = pixbuf_with_cache_new (_tmp10_, pixbuf);
		_pixbuf_with_cache_unref0 (self->priv->pixbufCache);
		self->priv->pixbufCache = _tmp11_;
		_tmp12_ = self->priv->pixbufCache;
		_tmp13_ = _pixbuf_with_cache_ref0 (_tmp12_);
		result = _tmp13_;
		_pixbuf_with_cache_unref0 (cache);
		return result;
	} else {
		result = cache;
		return result;
	}
	_pixbuf_with_cache_unref0 (cache);
}

void
line_marks_table_clear (LineMarksTable* self)
{
	gint _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = 0;
	self->lineMarks = g_renew (LineMark*, self->lineMarks, 0);
	(_tmp0_ > self->lineMarks_length1) ? memset (self->lineMarks + self->lineMarks_length1, 0, sizeof (LineMark*) * (_tmp0_ - self->lineMarks_length1)) : NULL;
	self->lineMarks_length1 = _tmp0_;
	self->_lineMarks_size_ = _tmp0_;
}

static gpointer
_line_mark_ref0 (gpointer self)
{
	return self ? line_mark_ref (self) : NULL;
}

static void
line_marks_table_update_line_marks_line_column_cache (LineMarksTable* self)
{
	g_return_if_fail (self != NULL);
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp0_ = FALSE;
			_tmp0_ = TRUE;
			while (TRUE) {
				LineMark** _tmp2_;
				gint _tmp2__length1;
				LineMark* mark = NULL;
				LineMark** _tmp3_;
				gint _tmp3__length1;
				LineMark* _tmp4_;
				LineMark* _tmp5_;
				LineMark* _tmp6_;
				if (!_tmp0_) {
					gint _tmp1_;
					_tmp1_ = i;
					i = _tmp1_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp2_ = self->lineMarks;
				_tmp2__length1 = self->lineMarks_length1;
				if (!(i < _tmp2__length1)) {
					break;
				}
				_tmp3_ = self->lineMarks;
				_tmp3__length1 = self->lineMarks_length1;
				_tmp4_ = _tmp3_[i];
				_tmp5_ = _line_mark_ref0 (_tmp4_);
				mark = _tmp5_;
				_tmp6_ = mark;
				line_mark_update_line_column_cache (_tmp6_);
				_line_mark_unref0 (mark);
			}
		}
	}
}

static gint
line_marks_table_compare_line_marks (LineMark** m1,
                                     LineMark** m2)
{
	gint result = 0;
	gint _tmp0_ = 0;
	gint _result_ = 0;
	if ((*m1)->line == (*m2)->line) {
		_tmp0_ = (*m1)->column - (*m2)->column;
	} else {
		_tmp0_ = (*m1)->line - (*m2)->line;
	}
	_result_ = _tmp0_;
	result = _result_;
	return result;
}

static gint
_line_marks_table_compare_line_marks_gcompare_data_func (gconstpointer a,
                                                         gconstpointer b,
                                                         gpointer self)
{
	gint result;
	result = line_marks_table_compare_line_marks (a, b);
	return result;
}

static void
line_marks_table_sort_line_marks (LineMarksTable* self)
{
	g_return_if_fail (self != NULL);
	if (!self->priv->sorted) {
		LineMark** _tmp0_;
		gint _tmp0__length1;
		LineMark** _tmp1_;
		gint _tmp1__length1;
		line_marks_table_update_line_marks_line_column_cache (self);
		_tmp0_ = self->lineMarks;
		_tmp0__length1 = self->lineMarks_length1;
		_tmp1_ = self->lineMarks;
		_tmp1__length1 = self->lineMarks_length1;
		g_qsort_with_data ((gconstpointer) _tmp0_, _tmp1__length1, (gsize) sizeof (LineMark*), (GCompareDataFunc) _line_marks_table_compare_line_marks_gcompare_data_func, NULL);
		self->priv->sorted = TRUE;
	}
}

static void
_vala_array_add1 (LineMark** * array,
                  int* length,
                  int* size,
                  LineMark* value)
{
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (LineMark*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}

void
line_marks_table_add_line_mark (LineMarksTable* self,
                                GtkTextMark* textMark,
                                GdkPixbuf* pixbuf)
{
	LineMark** _tmp0_;
	gint _tmp0__length1;
	PixbufWithCache* _tmp1_;
	PixbufWithCache* _tmp2_;
	LineMark* _tmp3_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (textMark != NULL);
	g_return_if_fail (pixbuf != NULL);
	_tmp0_ = self->lineMarks;
	_tmp0__length1 = self->lineMarks_length1;
	_tmp1_ = line_marks_table_get_pixbuf_with_cache (self, pixbuf);
	_tmp2_ = _tmp1_;
	_tmp3_ = line_mark_new (textMark, _tmp2_);
	_vala_array_add1 (&self->lineMarks, &self->lineMarks_length1, &self->_lineMarks_size_, _tmp3_);
	_pixbuf_with_cache_unref0 (_tmp2_);
	self->priv->sorted = FALSE;
}

void
line_marks_table_add_line_mark_at_line_offset (LineMarksTable* self,
                                               GtkTextBuffer* buffer,
                                               gint line,
                                               gint offset,
                                               GdkPixbuf* pixbuf)
{
	GtkTextIter iter = {0};
	GtkTextIter _tmp0_ = {0};
	GtkTextMark* mark = NULL;
	GtkTextIter _tmp1_;
	GtkTextMark* _tmp2_;
	GtkTextMark* _tmp3_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (buffer != NULL);
	g_return_if_fail (pixbuf != NULL);
	gtk_text_buffer_get_iter_at_line_offset (buffer, &_tmp0_, line, offset);
	iter = _tmp0_;
	_tmp1_ = iter;
	_tmp2_ = gtk_text_buffer_create_mark (buffer, NULL, &_tmp1_, TRUE);
	_tmp3_ = _g_object_ref0 (_tmp2_);
	mark = _tmp3_;
	line_marks_table_add_line_mark (self, mark, pixbuf);
	_g_object_unref0 (mark);
}

static gint
line_marks_table_measure_line_height (LineMarksTable* self,
                                      GtkSourceView* view)
{
	gint result = 0;
	PangoLayout* layout = NULL;
	PangoLayout* _tmp0_;
	gint height = 0;
	PangoLayout* _tmp1_;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (view != NULL, 0);
	_tmp0_ = gtk_widget_create_pango_layout ((GtkWidget*) view, "QWERTY");
	layout = _tmp0_;
	height = 12;
	_tmp1_ = layout;
	if (_tmp1_ != NULL) {
		PangoLayout* _tmp2_;
		gint _tmp3_ = 0;
		_tmp2_ = layout;
		pango_layout_get_pixel_size (_tmp2_, NULL, &_tmp3_);
		height = _tmp3_;
	}
	self->lineHeight = height - 2;
	result = self->lineHeight;
	_g_object_unref0 (layout);
	return result;
}

static gint
line_marks_table_get_max_nb_marks_on_line (LineMarksTable* self,
                                           GtkTextBuffer* buffer)
{
	gint result = 0;
	gint max = 0;
	gint currentLine = 0;
	gint nb = 0;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (buffer != NULL, 0);
	max = 0;
	currentLine = -1;
	nb = 0;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp0_ = FALSE;
			_tmp0_ = TRUE;
			while (TRUE) {
				LineMark** _tmp2_;
				gint _tmp2__length1;
				LineMark* mark = NULL;
				LineMark** _tmp3_;
				gint _tmp3__length1;
				LineMark* _tmp4_;
				LineMark* _tmp5_;
				GtkTextMark* m = NULL;
				LineMark* _tmp6_;
				GtkTextMark* _tmp7_;
				GtkTextMark* _tmp8_;
				GtkTextMark* _tmp9_;
				GtkTextBuffer* _tmp10_;
				if (!_tmp0_) {
					gint _tmp1_;
					_tmp1_ = i;
					i = _tmp1_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp2_ = self->lineMarks;
				_tmp2__length1 = self->lineMarks_length1;
				if (!(i < _tmp2__length1)) {
					break;
				}
				_tmp3_ = self->lineMarks;
				_tmp3__length1 = self->lineMarks_length1;
				_tmp4_ = _tmp3_[i];
				_tmp5_ = _line_mark_ref0 (_tmp4_);
				mark = _tmp5_;
				_tmp6_ = mark;
				_tmp7_ = _tmp6_->textMark;
				_tmp8_ = _g_object_ref0 (_tmp7_);
				m = _tmp8_;
				_tmp9_ = m;
				_tmp10_ = gtk_text_mark_get_buffer (_tmp9_);
				if (_tmp10_ == buffer) {
					GtkTextIter iter = {0};
					GtkTextMark* _tmp11_;
					GtkTextIter _tmp12_ = {0};
					_tmp11_ = m;
					gtk_text_buffer_get_iter_at_mark (buffer, &_tmp12_, _tmp11_);
					iter = _tmp12_;
					if (gtk_text_iter_get_line (&iter) == currentLine) {
						gint _tmp13_;
						_tmp13_ = nb;
						nb = _tmp13_ + 1;
					} else {
						currentLine = gtk_text_iter_get_line (&iter);
						nb = 1;
					}
					if (nb > max) {
						max = nb;
					}
				}
				_g_object_unref0 (m);
				_line_mark_unref0 (mark);
			}
		}
	}
	result = max;
	return result;
}

static void
line_marks_table_size_func (LineMarksTable* self,
                            GtkSourceGutter* gutter,
                            GtkCellRenderer* renderer)
{
	GtkSourceView* view = NULL;
	GtkSourceView* _tmp0_;
	GtkSourceView* _tmp1_;
	GtkTextBuffer* _tmp2_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (gutter != NULL);
	g_return_if_fail (renderer != NULL);
	line_marks_table_sort_line_marks (self);
	g_object_get (gutter, "view", &_tmp0_, NULL);
	_tmp1_ = _tmp0_;
	view = _tmp1_;
	_tmp2_ = gtk_text_view_get_buffer ((GtkTextView*) view);
	self->rendererWidth = line_marks_table_measure_line_height (self, view) * line_marks_table_get_max_nb_marks_on_line (self, _tmp2_);
	_g_object_unref0 (self->lastBuffer);
	self->lastBuffer = NULL;
	self->lastLineNumber = -1;
	self->nextIndex = 0;
	_g_object_unref0 (view);
}

static void
line_marks_table_data_func (LineMarksTable* self,
                            GtkSourceGutter* gutter,
                            GtkCellRenderer* renderer,
                            gint lineNumber,
                            gboolean currentLine)
{
	g_return_if_fail (self != NULL);
	g_return_if_fail (gutter != NULL);
	g_return_if_fail (renderer != NULL);
	self->lineNumber = lineNumber;
}

static void
_line_marks_table_size_func_gtk_source_gutter_size_func (GtkSourceGutter* gutter,
                                                         GtkCellRenderer* cell,
                                                         gpointer self)
{
	line_marks_table_size_func ((LineMarksTable*) self, gutter, cell);
}

static void
_line_marks_table_data_func_gtk_source_gutter_data_func (GtkSourceGutter* gutter,
                                                         GtkCellRenderer* cell,
                                                         gint line_number,
                                                         gboolean current_line,
                                                         gpointer self)
{
	line_marks_table_data_func ((LineMarksTable*) self, gutter, cell, line_number, current_line);
}

void
line_marks_table_show_in_source_view (LineMarksTable* self,
                                      GtkSourceView* sourceView)
{
	GtkSourceGutter* gutter = NULL;
	GtkSourceGutter* _tmp0_;
	GtkSourceGutter* _tmp1_;
	LineMarksRenderer* renderer = NULL;
	LineMarksRenderer* _tmp2_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (sourceView != NULL);
	_tmp0_ = gtk_source_view_get_gutter (sourceView, GTK_TEXT_WINDOW_LEFT);
	_tmp1_ = _g_object_ref0 (_tmp0_);
	gutter = _tmp1_;
	_tmp2_ = line_marks_renderer_new (self, gutter);
	g_object_ref_sink (_tmp2_);
	renderer = _tmp2_;
	gtk_source_gutter_insert (gutter, (GtkCellRenderer*) renderer, 0);
	gtk_source_gutter_set_cell_size_func (gutter, (GtkCellRenderer*) renderer, _line_marks_table_size_func_gtk_source_gutter_size_func, g_object_ref (self), g_object_unref);
	gtk_source_gutter_set_cell_data_func (gutter, (GtkCellRenderer*) renderer, _line_marks_table_data_func_gtk_source_gutter_data_func, g_object_ref (self), g_object_unref);
	_g_object_unref0 (renderer);
	_g_object_unref0 (gutter);
}

LineMarksTable*
line_marks_table_construct (GType object_type)
{
	LineMarksTable * self = NULL;
	self = (LineMarksTable*) g_object_new (object_type, NULL);
	return self;
}

LineMarksTable*
line_marks_table_new (void)
{
	return line_marks_table_construct (TYPE_LINE_MARKS_TABLE);
}

static void
line_marks_table_class_init (LineMarksTableClass * klass,
                             gpointer klass_data)
{
	line_marks_table_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &LineMarksTable_private_offset);
	G_OBJECT_CLASS (klass)->finalize = line_marks_table_finalize;
}

static void
line_marks_table_instance_init (LineMarksTable * self,
                                gpointer klass)
{
	LineMark** _tmp0_;
	self->priv = line_marks_table_get_instance_private (self);
	_tmp0_ = g_new0 (LineMark*, 0 + 1);
	self->lineMarks = _tmp0_;
	self->lineMarks_length1 = 0;
	self->_lineMarks_size_ = self->lineMarks_length1;
	self->priv->sorted = TRUE;
	self->lineHeight = 0;
	self->rendererWidth = 0;
	self->lastBuffer = NULL;
	self->lastLineNumber = -1;
	self->nextIndex = 0;
	self->lineNumber = -1;
}

static void
line_marks_table_finalize (GObject * obj)
{
	LineMarksTable * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_LINE_MARKS_TABLE, LineMarksTable);
	_pixbuf_with_cache_unref0 (self->priv->pixbufCache);
	self->lineMarks = (_vala_array_free (self->lineMarks, self->lineMarks_length1, (GDestroyNotify) line_mark_unref), NULL);
	_g_object_unref0 (self->lastBuffer);
	G_OBJECT_CLASS (line_marks_table_parent_class)->finalize (obj);
}

GType
line_marks_table_get_type (void)
{
	static volatile gsize line_marks_table_type_id__volatile = 0;
	if (g_once_init_enter (&line_marks_table_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LineMarksTableClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) line_marks_table_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LineMarksTable), 0, (GInstanceInitFunc) line_marks_table_instance_init, NULL };
		GType line_marks_table_type_id;
		line_marks_table_type_id = g_type_register_static (G_TYPE_OBJECT, "LineMarksTable", &g_define_type_info, 0);
		LineMarksTable_private_offset = g_type_add_instance_private (line_marks_table_type_id, sizeof (LineMarksTablePrivate));
		g_once_init_leave (&line_marks_table_type_id__volatile, line_marks_table_type_id);
	}
	return line_marks_table_type_id__volatile;
}

static inline gpointer
line_marks_renderer_get_instance_private (LineMarksRenderer* self)
{
	return G_STRUCT_MEMBER_P (self, LineMarksRenderer_private_offset);
}

LineMarksRenderer*
line_marks_renderer_construct (GType object_type,
                               LineMarksTable* table,
                               GtkSourceGutter* gutter)
{
	LineMarksRenderer * self = NULL;
	LineMarksTable* _tmp0_;
	GtkSourceGutter* _tmp1_;
	g_return_val_if_fail (table != NULL, NULL);
	g_return_val_if_fail (gutter != NULL, NULL);
	self = (LineMarksRenderer*) g_object_new (object_type, NULL);
	_tmp0_ = _g_object_ref0 (table);
	_g_object_unref0 (self->priv->table);
	self->priv->table = _tmp0_;
	_tmp1_ = _g_object_ref0 (gutter);
	_g_object_unref0 (self->priv->gutter);
	self->priv->gutter = _tmp1_;
	return self;
}

LineMarksRenderer*
line_marks_renderer_new (LineMarksTable* table,
                         GtkSourceGutter* gutter)
{
	return line_marks_renderer_construct (TYPE_LINE_MARKS_RENDERER, table, gutter);
}

static void
line_marks_renderer_real_get_size (GtkCellRenderer* base,
                                   GtkWidget* widget,
                                   GdkRectangle* cell_area,
                                   gint* x_offset,
                                   gint* y_offset,
                                   gint* width,
                                   gint* height)
{
	LineMarksRenderer * self;
	gint _vala_x_offset = 0;
	gint _vala_y_offset = 0;
	gint _vala_width = 0;
	gint _vala_height = 0;
	LineMarksTable* _tmp0_;
	LineMarksTable* _tmp1_;
	self = (LineMarksRenderer*) base;
	g_return_if_fail (widget != NULL);
	_vala_x_offset = 0;
	_vala_y_offset = 0;
	_tmp0_ = self->priv->table;
	_vala_width = _tmp0_->rendererWidth;
	_tmp1_ = self->priv->table;
	_vala_height = _tmp1_->lineHeight;
	if (x_offset) {
		*x_offset = _vala_x_offset;
	}
	if (y_offset) {
		*y_offset = _vala_y_offset;
	}
	if (width) {
		*width = _vala_width;
	}
	if (height) {
		*height = _vala_height;
	}
}

static void
line_marks_renderer_real_render (GtkCellRenderer* base,
                                 GdkWindow* window,
                                 GtkWidget* widget,
                                 GdkRectangle* background_area,
                                 GdkRectangle* cell_area,
                                 GdkRectangle* expose_area,
                                 GtkCellRendererState flags)
{
	LineMarksRenderer * self;
	cairo_t* ctx = NULL;
	cairo_t* _tmp0_;
	gint x = 0;
	GdkRectangle _tmp1_;
	GtkTextBuffer* buffer = NULL;
	GtkSourceGutter* _tmp2_;
	GtkSourceView* _tmp3_;
	GtkSourceView* _tmp4_;
	GtkSourceView* _tmp5_;
	GtkTextBuffer* _tmp6_;
	GtkTextBuffer* _tmp7_;
	GtkTextBuffer* _tmp8_;
	gboolean _tmp9_ = FALSE;
	LineMarksTable* _tmp10_;
	GtkTextBuffer* _tmp11_;
	GtkTextBuffer* _tmp12_;
	LineMarksTable* _tmp55_;
	LineMarksTable* _tmp56_;
	self = (LineMarksRenderer*) base;
	g_return_if_fail (window != NULL);
	g_return_if_fail (widget != NULL);
	g_return_if_fail (background_area != NULL);
	g_return_if_fail (cell_area != NULL);
	g_return_if_fail (expose_area != NULL);
	_tmp0_ = gdk_cairo_create ((GdkDrawable*) window);
	ctx = _tmp0_;
	_tmp1_ = *background_area;
	x = _tmp1_.x;
	_tmp2_ = self->priv->gutter;
	g_object_get (_tmp2_, "view", &_tmp3_, NULL);
	_tmp4_ = _tmp3_;
	_tmp5_ = _tmp4_;
	_tmp6_ = gtk_text_view_get_buffer ((GtkTextView*) _tmp5_);
	_tmp7_ = _g_object_ref0 (_tmp6_);
	_tmp8_ = _tmp7_;
	_g_object_unref0 (_tmp5_);
	buffer = _tmp8_;
	_tmp10_ = self->priv->table;
	_tmp11_ = _tmp10_->lastBuffer;
	_tmp12_ = buffer;
	if (_tmp11_ != _tmp12_) {
		_tmp9_ = TRUE;
	} else {
		LineMarksTable* _tmp13_;
		LineMarksTable* _tmp14_;
		_tmp13_ = self->priv->table;
		_tmp14_ = self->priv->table;
		_tmp9_ = _tmp13_->lastLineNumber >= _tmp14_->lineNumber;
	}
	if (_tmp9_) {
		LineMarksTable* _tmp15_;
		GtkTextBuffer* _tmp16_;
		GtkTextBuffer* _tmp17_;
		LineMarksTable* _tmp18_;
		_tmp15_ = self->priv->table;
		_tmp16_ = buffer;
		_tmp17_ = _g_object_ref0 (_tmp16_);
		_g_object_unref0 (_tmp15_->lastBuffer);
		_tmp15_->lastBuffer = _tmp17_;
		_tmp18_ = self->priv->table;
		_tmp18_->nextIndex = 0;
	}
	{
		gboolean _tmp19_ = FALSE;
		_tmp19_ = TRUE;
		while (TRUE) {
			LineMarksTable* _tmp22_;
			LineMarksTable* _tmp23_;
			LineMark** _tmp24_;
			gint _tmp24__length1;
			LineMark* mark = NULL;
			LineMarksTable* _tmp25_;
			LineMark** _tmp26_;
			gint _tmp26__length1;
			LineMarksTable* _tmp27_;
			LineMark* _tmp28_;
			LineMark* _tmp29_;
			GtkTextMark* m = NULL;
			LineMark* _tmp30_;
			GtkTextMark* _tmp31_;
			GtkTextMark* _tmp32_;
			GtkTextMark* _tmp33_;
			GtkTextBuffer* _tmp34_;
			GtkTextBuffer* _tmp35_;
			if (!_tmp19_) {
				LineMarksTable* _tmp20_;
				gint _tmp21_;
				_tmp20_ = self->priv->table;
				_tmp21_ = _tmp20_->nextIndex;
				_tmp20_->nextIndex = _tmp21_ + 1;
			}
			_tmp19_ = FALSE;
			_tmp22_ = self->priv->table;
			_tmp23_ = self->priv->table;
			_tmp24_ = _tmp23_->lineMarks;
			_tmp24__length1 = _tmp23_->lineMarks_length1;
			if (!(_tmp22_->nextIndex < _tmp24__length1)) {
				break;
			}
			_tmp25_ = self->priv->table;
			_tmp26_ = _tmp25_->lineMarks;
			_tmp26__length1 = _tmp25_->lineMarks_length1;
			_tmp27_ = self->priv->table;
			_tmp28_ = _tmp26_[_tmp27_->nextIndex];
			_tmp29_ = _line_mark_ref0 (_tmp28_);
			mark = _tmp29_;
			_tmp30_ = mark;
			_tmp31_ = _tmp30_->textMark;
			_tmp32_ = _g_object_ref0 (_tmp31_);
			m = _tmp32_;
			_tmp33_ = m;
			_tmp34_ = gtk_text_mark_get_buffer (_tmp33_);
			_tmp35_ = buffer;
			if (_tmp34_ == _tmp35_) {
				GtkTextIter iter = {0};
				GtkTextBuffer* _tmp36_;
				GtkTextMark* _tmp37_;
				GtkTextIter _tmp38_ = {0};
				LineMarksTable* _tmp39_;
				LineMarksTable* _tmp40_;
				_tmp36_ = buffer;
				_tmp37_ = m;
				gtk_text_buffer_get_iter_at_mark (_tmp36_, &_tmp38_, _tmp37_);
				iter = _tmp38_;
				_tmp39_ = self->priv->table;
				if (gtk_text_iter_get_line (&iter) > _tmp39_->lineNumber) {
					_g_object_unref0 (m);
					_line_mark_unref0 (mark);
					break;
				}
				_tmp40_ = self->priv->table;
				if (gtk_text_iter_get_line (&iter) == _tmp40_->lineNumber) {
					cairo_t* _tmp41_;
					GdkRectangle _tmp42_;
					LineMarksTable* _tmp43_;
					LineMarksTable* _tmp44_;
					GdkRectangle _tmp45_ = {0};
					cairo_t* _tmp46_;
					LineMark* _tmp47_;
					PixbufWithCache* _tmp48_;
					LineMarksTable* _tmp49_;
					GdkPixbuf* _tmp50_;
					GdkPixbuf* _tmp51_;
					GdkRectangle _tmp52_;
					cairo_t* _tmp53_;
					LineMarksTable* _tmp54_;
					_tmp41_ = ctx;
					_tmp42_ = *background_area;
					_tmp43_ = self->priv->table;
					_tmp44_ = self->priv->table;
					memset (&_tmp45_, 0, sizeof (GdkRectangle));
					_tmp45_.x = x + 1;
					_tmp45_.y = _tmp42_.y + 1;
					_tmp45_.width = _tmp43_->lineHeight - 2;
					_tmp45_.height = _tmp44_->lineHeight - 2;
					gdk_cairo_rectangle (_tmp41_, &_tmp45_);
					_tmp46_ = ctx;
					_tmp47_ = mark;
					_tmp48_ = _tmp47_->pixbuf;
					_tmp49_ = self->priv->table;
					_tmp50_ = pixbuf_with_cache_get_at_size (_tmp48_, _tmp49_->lineHeight - 2);
					_tmp51_ = _tmp50_;
					_tmp52_ = *background_area;
					gdk_cairo_set_source_pixbuf (_tmp46_, _tmp51_, (gdouble) (x + 1), (gdouble) (_tmp52_.y + 1));
					_g_object_unref0 (_tmp51_);
					_tmp53_ = ctx;
					cairo_fill (_tmp53_);
					_tmp54_ = self->priv->table;
					x = x + _tmp54_->lineHeight;
				}
			}
			_g_object_unref0 (m);
			_line_mark_unref0 (mark);
		}
	}
	_tmp55_ = self->priv->table;
	_tmp56_ = self->priv->table;
	_tmp55_->lastLineNumber = _tmp56_->lineNumber;
	_g_object_unref0 (buffer);
	_cairo_destroy0 (ctx);
}

static void
line_marks_renderer_class_init (LineMarksRendererClass * klass,
                                gpointer klass_data)
{
	line_marks_renderer_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &LineMarksRenderer_private_offset);
	((GtkCellRendererClass *) klass)->get_size = (void (*) (GtkCellRenderer*, GtkWidget*, GdkRectangle*, gint*, gint*, gint*, gint*)) line_marks_renderer_real_get_size;
	((GtkCellRendererClass *) klass)->render = (void (*) (GtkCellRenderer*, GdkWindow*, GtkWidget*, GdkRectangle*, GdkRectangle*, GdkRectangle*, GtkCellRendererState)) line_marks_renderer_real_render;
	G_OBJECT_CLASS (klass)->finalize = line_marks_renderer_finalize;
}

static void
line_marks_renderer_instance_init (LineMarksRenderer * self,
                                   gpointer klass)
{
	self->priv = line_marks_renderer_get_instance_private (self);
}

static void
line_marks_renderer_finalize (GObject * obj)
{
	LineMarksRenderer * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_LINE_MARKS_RENDERER, LineMarksRenderer);
	_g_object_unref0 (self->priv->table);
	_g_object_unref0 (self->priv->gutter);
	G_OBJECT_CLASS (line_marks_renderer_parent_class)->finalize (obj);
}

GType
line_marks_renderer_get_type (void)
{
	static volatile gsize line_marks_renderer_type_id__volatile = 0;
	if (g_once_init_enter (&line_marks_renderer_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LineMarksRendererClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) line_marks_renderer_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LineMarksRenderer), 0, (GInstanceInitFunc) line_marks_renderer_instance_init, NULL };
		GType line_marks_renderer_type_id;
		line_marks_renderer_type_id = g_type_register_static (GTK_TYPE_CELL_RENDERER, "LineMarksRenderer", &g_define_type_info, 0);
		LineMarksRenderer_private_offset = g_type_add_instance_private (line_marks_renderer_type_id, sizeof (LineMarksRendererPrivate));
		g_once_init_leave (&line_marks_renderer_type_id__volatile, line_marks_renderer_type_id);
	}
	return line_marks_renderer_type_id__volatile;
}

static inline gpointer
source_gutter_text_column_get_instance_private (SourceGutterTextColumn* self)
{
	return G_STRUCT_MEMBER_P (self, SourceGutterTextColumn_private_offset);
}

SourceGutterTextColumn*
source_gutter_text_column_construct (GType object_type,
                                     const gchar* sizeText,
                                     gfloat xalign)
{
	SourceGutterTextColumn * self = NULL;
	gchar* _tmp0_;
	GtkCellRendererText* _tmp1_;
	GtkCellRendererText* _tmp2_;
	g_return_val_if_fail (sizeText != NULL, NULL);
	self = (SourceGutterTextColumn*) g_object_new (object_type, NULL);
	_tmp0_ = g_strdup (sizeText);
	_g_free0 (self->priv->sizeText);
	self->priv->sizeText = _tmp0_;
	_tmp1_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
	g_object_ref_sink (_tmp1_);
	_g_object_unref0 (self->priv->renderer);
	self->priv->renderer = _tmp1_;
	_tmp2_ = self->priv->renderer;
	g_object_set ((GtkCellRenderer*) _tmp2_, "xalign", xalign, NULL);
	return self;
}

SourceGutterTextColumn*
source_gutter_text_column_new (const gchar* sizeText,
                               gfloat xalign)
{
	return source_gutter_text_column_construct (TYPE_SOURCE_GUTTER_TEXT_COLUMN, sizeText, xalign);
}

void
source_gutter_text_column_clear (SourceGutterTextColumn* self)
{
	gchar** _tmp0_;
	GtkSourceGutter** _tmp1_;
	gint _tmp1__length1;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_new0 (gchar*, 0 + 1);
	self->priv->lines = (_vala_array_free (self->priv->lines, self->priv->lines_length1, (GDestroyNotify) g_free), NULL);
	self->priv->lines = _tmp0_;
	self->priv->lines_length1 = 0;
	self->priv->_lines_size_ = self->priv->lines_length1;
	_tmp1_ = self->priv->gutters;
	_tmp1__length1 = self->priv->gutters_length1;
	{
		GtkSourceGutter** gutter_collection = NULL;
		gint gutter_collection_length1 = 0;
		gint _gutter_collection_size_ = 0;
		gint gutter_it = 0;
		gutter_collection = _tmp1_;
		gutter_collection_length1 = _tmp1__length1;
		for (gutter_it = 0; gutter_it < gutter_collection_length1; gutter_it = gutter_it + 1) {
			GtkSourceGutter* _tmp2_;
			GtkSourceGutter* gutter = NULL;
			_tmp2_ = _g_object_ref0 (gutter_collection[gutter_it]);
			gutter = _tmp2_;
			{
				GtkSourceGutter* _tmp3_;
				_tmp3_ = gutter;
				gtk_source_gutter_queue_draw (_tmp3_);
				_g_object_unref0 (gutter);
			}
		}
	}
}

static void
_vala_array_add2 (gchar** * array,
                  int* length,
                  int* size,
                  gchar* value)
{
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}

void
source_gutter_text_column_add_line (SourceGutterTextColumn* self,
                                    const gchar* line)
{
	gchar** _tmp0_;
	gint _tmp0__length1;
	gchar* _tmp1_;
	GtkSourceGutter** _tmp2_;
	gint _tmp2__length1;
	g_return_if_fail (self != NULL);
	g_return_if_fail (line != NULL);
	_tmp0_ = self->priv->lines;
	_tmp0__length1 = self->priv->lines_length1;
	_tmp1_ = g_strdup (line);
	_vala_array_add2 (&self->priv->lines, &self->priv->lines_length1, &self->priv->_lines_size_, _tmp1_);
	_tmp2_ = self->priv->gutters;
	_tmp2__length1 = self->priv->gutters_length1;
	{
		GtkSourceGutter** gutter_collection = NULL;
		gint gutter_collection_length1 = 0;
		gint _gutter_collection_size_ = 0;
		gint gutter_it = 0;
		gutter_collection = _tmp2_;
		gutter_collection_length1 = _tmp2__length1;
		for (gutter_it = 0; gutter_it < gutter_collection_length1; gutter_it = gutter_it + 1) {
			GtkSourceGutter* _tmp3_;
			GtkSourceGutter* gutter = NULL;
			_tmp3_ = _g_object_ref0 (gutter_collection[gutter_it]);
			gutter = _tmp3_;
			{
				GtkSourceGutter* _tmp4_;
				_tmp4_ = gutter;
				gtk_source_gutter_queue_draw (_tmp4_);
				_g_object_unref0 (gutter);
			}
		}
	}
}

static void
source_gutter_text_column_size_func (SourceGutterTextColumn* self,
                                     GtkSourceGutter* gutter,
                                     GtkCellRenderer* renderer_)
{
	GtkCellRendererText* _tmp0_;
	const gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (gutter != NULL);
	g_return_if_fail (renderer_ != NULL);
	_tmp0_ = self->priv->renderer;
	_tmp1_ = self->priv->sizeText;
	g_object_set (_tmp0_, "text", _tmp1_, NULL);
}

static void
source_gutter_text_column_data_func (SourceGutterTextColumn* self,
                                     GtkSourceGutter* gutter,
                                     GtkCellRenderer* renderer_,
                                     gint lineNumber,
                                     gboolean currentLine)
{
	const gchar* _tmp0_ = NULL;
	gchar** _tmp1_;
	gint _tmp1__length1;
	GtkCellRendererText* _tmp4_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (gutter != NULL);
	g_return_if_fail (renderer_ != NULL);
	_tmp1_ = self->priv->lines;
	_tmp1__length1 = self->priv->lines_length1;
	if (lineNumber < _tmp1__length1) {
		gchar** _tmp2_;
		gint _tmp2__length1;
		const gchar* _tmp3_;
		_tmp2_ = self->priv->lines;
		_tmp2__length1 = self->priv->lines_length1;
		_tmp3_ = _tmp2_[lineNumber];
		_tmp0_ = _tmp3_;
	} else {
		_tmp0_ = "";
	}
	_tmp4_ = self->priv->renderer;
	g_object_set (_tmp4_, "text", _tmp0_, NULL);
}

static void
_vala_array_add3 (GtkSourceGutter** * array,
                  int* length,
                  int* size,
                  GtkSourceGutter* value)
{
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (GtkSourceGutter*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}

static void
_source_gutter_text_column_size_func_gtk_source_gutter_size_func (GtkSourceGutter* gutter,
                                                                  GtkCellRenderer* cell,
                                                                  gpointer self)
{
	source_gutter_text_column_size_func ((SourceGutterTextColumn*) self, gutter, cell);
}

static void
_source_gutter_text_column_data_func_gtk_source_gutter_data_func (GtkSourceGutter* gutter,
                                                                  GtkCellRenderer* cell,
                                                                  gint line_number,
                                                                  gboolean current_line,
                                                                  gpointer self)
{
	source_gutter_text_column_data_func ((SourceGutterTextColumn*) self, gutter, cell, line_number, current_line);
}

void
source_gutter_text_column_show_in_source_view (SourceGutterTextColumn* self,
                                               GtkSourceView* sourceView)
{
	GtkSourceGutter* gutter = NULL;
	GtkSourceGutter* _tmp0_;
	GtkSourceGutter* _tmp1_;
	GtkSourceGutter** _tmp2_;
	gint _tmp2__length1;
	GtkSourceGutter* _tmp3_;
	GtkCellRendererText* _tmp4_;
	GtkCellRendererText* _tmp5_;
	GtkCellRendererText* _tmp6_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (sourceView != NULL);
	_tmp0_ = gtk_source_view_get_gutter (sourceView, GTK_TEXT_WINDOW_LEFT);
	_tmp1_ = _g_object_ref0 (_tmp0_);
	gutter = _tmp1_;
	_tmp2_ = self->priv->gutters;
	_tmp2__length1 = self->priv->gutters_length1;
	_tmp3_ = _g_object_ref0 (gutter);
	_vala_array_add3 (&self->priv->gutters, &self->priv->gutters_length1, &self->priv->_gutters_size_, _tmp3_);
	_tmp4_ = self->priv->renderer;
	gtk_source_gutter_insert (gutter, (GtkCellRenderer*) _tmp4_, -5);
	_tmp5_ = self->priv->renderer;
	gtk_source_gutter_set_cell_size_func (gutter, (GtkCellRenderer*) _tmp5_, _source_gutter_text_column_size_func_gtk_source_gutter_size_func, g_object_ref (self), g_object_unref);
	_tmp6_ = self->priv->renderer;
	gtk_source_gutter_set_cell_data_func (gutter, (GtkCellRenderer*) _tmp6_, _source_gutter_text_column_data_func_gtk_source_gutter_data_func, g_object_ref (self), g_object_unref);
	_g_object_unref0 (gutter);
}

static void
source_gutter_text_column_class_init (SourceGutterTextColumnClass * klass,
                                      gpointer klass_data)
{
	source_gutter_text_column_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &SourceGutterTextColumn_private_offset);
	G_OBJECT_CLASS (klass)->finalize = source_gutter_text_column_finalize;
}

static void
source_gutter_text_column_instance_init (SourceGutterTextColumn * self,
                                         gpointer klass)
{
	gchar** _tmp0_;
	self->priv = source_gutter_text_column_get_instance_private (self);
	_tmp0_ = g_new0 (gchar*, 0 + 1);
	self->priv->lines = _tmp0_;
	self->priv->lines_length1 = 0;
	self->priv->_lines_size_ = self->priv->lines_length1;
}

static void
source_gutter_text_column_finalize (GObject * obj)
{
	SourceGutterTextColumn * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_SOURCE_GUTTER_TEXT_COLUMN, SourceGutterTextColumn);
	_g_free0 (self->priv->sizeText);
	self->priv->lines = (_vala_array_free (self->priv->lines, self->priv->lines_length1, (GDestroyNotify) g_free), NULL);
	_g_object_unref0 (self->priv->renderer);
	self->priv->gutters = (_vala_array_free (self->priv->gutters, self->priv->gutters_length1, (GDestroyNotify) g_object_unref), NULL);
	G_OBJECT_CLASS (source_gutter_text_column_parent_class)->finalize (obj);
}

GType
source_gutter_text_column_get_type (void)
{
	static volatile gsize source_gutter_text_column_type_id__volatile = 0;
	if (g_once_init_enter (&source_gutter_text_column_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SourceGutterTextColumnClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) source_gutter_text_column_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SourceGutterTextColumn), 0, (GInstanceInitFunc) source_gutter_text_column_instance_init, NULL };
		GType source_gutter_text_column_type_id;
		source_gutter_text_column_type_id = g_type_register_static (G_TYPE_OBJECT, "SourceGutterTextColumn", &g_define_type_info, 0);
		SourceGutterTextColumn_private_offset = g_type_add_instance_private (source_gutter_text_column_type_id, sizeof (SourceGutterTextColumnPrivate));
		g_once_init_leave (&source_gutter_text_column_type_id__volatile, source_gutter_text_column_type_id);
	}
	return source_gutter_text_column_type_id__volatile;
}

static void
_vala_array_destroy (gpointer array,
                     gint array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gint array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

